# Generated by Django 4.2.10 on 2024-02-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_pdffile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['-upload_date']},
        ),
    ]
